---
title: "Class Objectives"
format: docx
editor: source
---

## Goals of this document

We will treat this class more like a job. There will not be tests or quizzes. Rather we will have conversations where we discuss how you are doing, and what you could improve on. You will reflect on your work, I will reply and we will discuss your grade from there.

We can discuss amendment of objectives as well, especially your personal objectives.

## Basic objectives

Over the course it is expected you will:

**Technically**

1.  Understand and implement the basic R-Studio -\> GitHub workflow; be able to collaborate using GitHub.
2.  Work in Quarto files; be able to adjust format and make output look nice.
3.  Complete https://swcarpentry.github.io/r-novice-gapminder/index.html
4.  Develop slideshow and website.
5.  Use code to further your own research.

**Communications**

1.  Provide respectful feedback in class and on Slack.
2.  Assist with issues on in class and on Slack.

## Personal objectives

* Get data from Sam and Adam to wrangle, visualize and explore
* Make workflowR website https://workflowr.github.io/workflowr/
* Write everything in Quarto docs

## Progress tracking

* Randy and Phillip met week of February 6, 2024 to discuss objectives and goals. 


##Reflection

I think for the class so far I deserve an A-. I have largely followed along with assignments and neccessary workload. I probably need to catch up a little bit on my website and figuring out what specifically I want to show on it. I will likely have to talk with Adam again to figure out what specifically he wants to try and find out from this Dataset and also what of his stuff he would be fine with me displaying.